### ISSUE TITLE
move all hash bins into S_MCTSL_learning dir

### ISSUE THREAD

**Issue by greenbean52** [Zerbinati/SugaR#5]
Hi, could put in code the path .\S_MCTSL_learning\
so that the bin files are not in the root thereby clearing up the root dir
also the S_MCTSL_learning.7z upzips with directory but the actually engine writes to the root dir?

so its just to change the code to look for its bins and more importantly to write its bins to
.\S_MCTSL_learning
and to update the Readme.md file to let all know that the bins go in .\S_MCTSL_learning

Cheers!
Greenbean

**Comment by Zerbinati** [comment]
As I explained to you, forget this code
This old code generated BIN files that only worked on the executable that generated them, they are not portable because the hashes are not as constant as at the beginning of the new code.
`   Zobrist::psq[14][14] = 5110446196942225801U;
   Zobrist::psq[14][15] = 2443501881669395127U;
   Zobrist::psq[14][16] = 6915148508579620831U;
   Zobrist::psq[14][17] = 9154422921438056207U;
   Zobrist::psq[14][18] = 3578030806440286511U;
   Zobrist::psq[14][19] = 15315801991440539300U;
   Zobrist::psq[14][20] = 7070866824836391168U;
   Zobrist::psq[14][21] = 14817924832942381111U;
   Zobrist::psq[14][22] = 3001446271118775643U;
   Zobrist::psq[14][23] = 13000642695841600636U;
   Zobrist::psq[14][24] = 14370567463871457833U;
   Zobrist::psq[14][25] = 11030064684553339453U;
   Zobrist::psq[14][26] = 14239970918075645415U;
   Zobrist::psq[14][27] = 9415971121016597759U;
   Zobrist::psq[14][28] = 6665243610733579451U;
   Zobrist::psq[14][29] = 12729882327349519727U;
   Zobrist::psq[14][30] = 127495542892799647U;
   Zobrist::psq[14][31] = 6044073010763988256U;
   Zobrist::psq[14][32] = 13007064564721953048U;
   Zobrist::psq[14][33] = 13888665226332397302U;
   Zobrist::psq[14][34] = 13536486134713258398U;
   Zobrist::psq[14][35] = 16493663995181111698U;
   Zobrist::psq[14][36] = 2130152061385863810U;
   Zobrist::psq[14][37] = 5369940202574713097U;
   Zobrist::psq[14][38] = 4976109024626592507U;
   Zobrist::psq[14][39] = 17662718886951473514U;
   Zobrist::psq[14][40] = 10194604604769366768U;
   Zobrist::psq[14][41] = 9434649875492567077U;
   Zobrist::psq[14][42] = 9275344374679790988U;
   Zobrist::psq[14][43] = 13950395516943844512U;
   Zobrist::psq[14][44] = 4634019286100624619U;
   Zobrist::psq[14][45] = 17524913661501655732U;
   Zobrist::psq[14][46] = 12758868016771465513U;
   Zobrist::psq[14][47] = 3127147764315865797U;
   Zobrist::psq[14][48] = 3960938717909563730U;
   Zobrist::psq[14][49] = 14869830638616427590U;
   Zobrist::psq[14][50] = 305185646789997459U;
   Zobrist::psq[14][51] = 4139658351799906696U;
   Zobrist::psq[14][52] = 272667046354598132U;
   Zobrist::psq[14][53] = 15621274402096728762U;
   Zobrist::psq[14][54] = 16483498129229512495U;
   Zobrist::psq[14][55] = 12953368655171389128U;
   Zobrist::psq[14][56] = 10678035399177741929U;
   Zobrist::psq[14][57] = 18049652274331575310U;
   Zobrist::psq[14][58] = 7975081034372805163U;
   Zobrist::psq[14][59] = 10522098076497821829U;
   Zobrist::psq[14][60] = 12606359703294662790U;
   Zobrist::psq[14][61] = 13924857104548874958U;
   Zobrist::psq[14][62] = 6566773282407180921U;
   Zobrist::psq[14][63] = 3452471826952569846U;
   Zobrist::enpassant[0] = 9031641776876329352U;
   Zobrist::enpassant[1] = 12228382040141709029U;
   Zobrist::enpassant[2] = 2494223668561036951U;
   Zobrist::enpassant[3] = 7849557628814744642U;
   Zobrist::enpassant[4] = 16000570245257669890U;
   Zobrist::enpassant[5] = 16614404541835922253U;
   Zobrist::enpassant[6] = 17787301719840479309U;
   Zobrist::enpassant[7] = 6371708097697762807U;
   Zobrist::castling[0] = 7487338029351702425U;
   Zobrist::castling[1] = 10138645747811604478U;
   Zobrist::castling[2] = 16332212992845378228U;
   Zobrist::castling[3] = 6795873897769436611U;
   Zobrist::castling[4] = 4906379431808431525U;
   Zobrist::castling[5] = 895963052000028445U;
   Zobrist::castling[6] = 9908024112921185340U;
   Zobrist::castling[7] = 11968150447396703004U;
   Zobrist::castling[8] = 9479661950789363348U;
   Zobrist::castling[9] = 13855803985643744043U;
   Zobrist::castling[10] = 10705462234079318642U;
   Zobrist::castling[11] = 15193185854920610048U;
   Zobrist::castling[12] = 11090572498526290765U;
   Zobrist::castling[13] = 2577199524176359085U;
   Zobrist::castling[14] = 14147118971151220805U;
   Zobrist::castling[15] = 7849635286513694150U;
   Zobrist::side = 11598212307497933772U;
   Zobrist::noPawns = 11773087935368354602U;
   Key MyCR[16];
   for (int cr = NO_CASTLING; cr <= ANY_CASTLING; ++cr)
   {
      MyCR[cr] = Zobrist::castling[cr];
   }

   for (int cr = NO_CASTLING; cr <= ANY_CASTLING; ++cr)
   {
      Zobrist::castling[cr] = 0;
      Bitboard b = cr;
      while (b)
      {
         Key k = Zobrist::castling[1ULL << pop_lsb(&b)];
         Zobrist::castling[cr] ^= k ? k : MyCR[cr];
      }
   }`
